# -*- coding: utf-8 -*-
"""chatbot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtLqh29IhGjN-GN03xi7b8j-r1CEJfFZ
"""

def get_response(user_input):
    user_input = user_input.lower().strip()

    if user_input in ["hello", "hi", "hey"]:
        return "Hi! 👋"
    elif user_input in ["how are you", "how r u", "how's it going"]:
        return "I'm fine, thanks! How about you?"
    elif user_input in ["i'm good", "i am good", "good", "fine"]:
        return "Glad to hear that!"
    elif user_input in ["what's your name", "who are you"]:
        return "I'm a simple rule-based chatbot built for CodeAlpha Task 4."
    elif user_input in ["thanks", "thank you"]:
        return "You're welcome!"
    elif user_input in ["bye", "goodbye", "exit", "quit"]:
        return "Goodbye! Have a great day!"
    else:
        return "Sorry, I didn't understand that. Try saying hello, how are you, what's your name, thanks, or bye."

def run_chatbot():
    print("Chatbot started! Type 'bye' to exit.")
    print("-" * 30)
    while True:
        user_input = input("You: ")
        response = get_response(user_input)
        print("Bot:", response)

        if user_input.lower().strip() in ["bye", "goodbye", "exit", "quit"]:
            break

run_chatbot()